[package]
name = "reaper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-wrap-err.workspace = true
enumflags2.workspace = true
heapless.workspace = true
tap.workspace = true
